import = ["~/.config/alacritty/gruvbox_material_hard_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
dynamic_padding = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 14

